apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-loadbalancer
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: GCP
      name: http
  selector:
    app.kubernetes.io/instance: foo
    app.kubernetes.io/name: bar
